#!/bin/sh
#!/usr/bin/env bash

source $(poetry env info --path)/Scripts/activate
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")
exec python -mpre_commit "${ARGS[@]}"